version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker Image
          command: docker build . -f ./Dockerfile -t georgevella/build-aspnetcore-node
      - run:
          name: Push Docker Image
          command: docker push georgevella/build-aspnetcore-node